// <auto-generated />
using System;
using GeradorApostasLotofacil.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeradorApostasLotofacil.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GeradorApostasLotofacil.Domain.ApostaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataApuracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Apostas");
                });

            modelBuilder.Entity("GeradorApostasLotofacil.Domain.JogoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApostaId")
                        .HasColumnType("int");

                    b.Property<int>("DecimoNumero")
                        .HasColumnType("int");

                    b.Property<int>("DecimoPrimeiroNumero")
                        .HasColumnType("int");

                    b.Property<int>("DecimoQuartoNumero")
                        .HasColumnType("int");

                    b.Property<int>("DecimoQuintoNumero")
                        .HasColumnType("int");

                    b.Property<int>("DecimoSegundoNumero")
                        .HasColumnType("int");

                    b.Property<int>("DecimoTerceiroNumero")
                        .HasColumnType("int");

                    b.Property<int>("NonoNumero")
                        .HasColumnType("int");

                    b.Property<int>("OitavoNumero")
                        .HasColumnType("int");

                    b.Property<int>("PrimeiroNumero")
                        .HasColumnType("int");

                    b.Property<int>("QuartoNumero")
                        .HasColumnType("int");

                    b.Property<int>("QuintoNumero")
                        .HasColumnType("int");

                    b.Property<int>("SegundoNumero")
                        .HasColumnType("int");

                    b.Property<int>("SetimoNumero")
                        .HasColumnType("int");

                    b.Property<int>("SextoNumero")
                        .HasColumnType("int");

                    b.Property<int>("TerceiroNumero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApostaId");

                    b.ToTable("JogoModel");
                });

            modelBuilder.Entity("GeradorApostasLotofacil.Domain.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GeradorApostasLotofacil.Domain.ApostaModel", b =>
                {
                    b.HasOne("GeradorApostasLotofacil.Domain.UsuarioModel", "Usuario")
                        .WithMany("Apostas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GeradorApostasLotofacil.Domain.JogoModel", b =>
                {
                    b.HasOne("GeradorApostasLotofacil.Domain.ApostaModel", "Aposta")
                        .WithMany("Jogos")
                        .HasForeignKey("ApostaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aposta");
                });

            modelBuilder.Entity("GeradorApostasLotofacil.Domain.ApostaModel", b =>
                {
                    b.Navigation("Jogos");
                });

            modelBuilder.Entity("GeradorApostasLotofacil.Domain.UsuarioModel", b =>
                {
                    b.Navigation("Apostas");
                });
#pragma warning restore 612, 618
        }
    }
}
